---
title: "Great Barrier Reef seabird foraging mapper"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=F, warning=F, message=F}
library(raster)
library(dplyr)
library(sf)
library(leaflet)

#read in data
for_rad<-read_sf('C:/seabirds/data/GIS/foraging_radii.shp')
# add sp colours
for_rad$md_spgr<-factor(for_rad$md_spgr, levels=c("BRBO", 'MABO', 'RFBO', 'FRBD', 'TRBD', 'WTST', "WTLG", "SOTE" , 'NODD', 'TERN'))
for_rad$spcol<-recode(for_rad$md_spgr, "BRBO"='#8dd3c7','MABO'='#ffffb3','RFBO'='#bebada','FRBD'='#fb8072', 'TRBD'='#80b1d3',
                      'WTST'='#fdb462','WTLG'='#b3de69',"SOTE"='#fccde5','NODD'='#d9d9d9','TERN'='#bc80bd')

colz<-read_sf('C:/seabirds/data/GIS/parks_gbr_cols.shp')
colz<-colz%>%group_by(dsgntn_n, site_nm)%>%summarise(species=paste(unique(species), collapse=', '))

pred_list<-list.files('C:/seabirds/data/modelling/GBR_preds', full.names=T)
pred_list<-pred_list[grep('indivSUM.tif', pred_list)]
mod_pred<-stack(pred_list)
hotspots<-raster('C:/seabirds/data/modelling/GBR_preds/hotspots.tif')
# merge colz by md_spgr and rd_class for gbr-wide plots
rad_diss<-for_rad%>%group_by(md_spgr, rd_clss)%>%summarize(geometry = st_union(geometry))

#normalize_rasts
hotspots<-(hotspots-min(values(hotspots), na.rm=T))/(max(values(hotspots), na.rm=T)-min(values(hotspots), na.rm=T))

brbo_ras<-subset(mod_pred, 'BRBO_indivSUM')
brbo_ras<-(brbo_ras-min(values(brbo_ras), na.rm=T))/(max(values(brbo_ras), na.rm=T)-min(values(brbo_ras), na.rm=T))
mabo_ras<-subset(mod_pred, 'MABO_indivSUM')
mabo_ras<-(mabo_ras-min(values(mabo_ras), na.rm=T))/(max(values(mabo_ras), na.rm=T)-min(values(mabo_ras), na.rm=T))
rfbo_ras<-subset(mod_pred, 'RFBO_indivSUM')
rfbo_ras<-(rfbo_ras-min(values(rfbo_ras), na.rm=T))/(max(values(rfbo_ras), na.rm=T)-min(values(rfbo_ras), na.rm=T))
frbd_ras<-subset(mod_pred, 'FRBD_indivSUM')
frbd_ras<-(frbd_ras-min(values(frbd_ras), na.rm=T))/(max(values(frbd_ras), na.rm=T)-min(values(frbd_ras), na.rm=T))
trbd_ras<-subset(mod_pred, 'TRBD_indivSUM')
trbd_ras<-(trbd_ras-min(values(trbd_ras), na.rm=T))/(max(values(trbd_ras), na.rm=T)-min(values(trbd_ras), na.rm=T))
wtst_ras<-subset(mod_pred, 'WTST_indivSUM')
wtst_ras<-(wtst_ras-min(values(wtst_ras), na.rm=T))/(max(values(wtst_ras), na.rm=T)-min(values(wtst_ras), na.rm=T))
wtlg_ras<-subset(mod_pred, 'WTLG_indivSUM')
wtlg_ras<-(wtlg_ras-min(values(wtlg_ras), na.rm=T))/(max(values(wtlg_ras), na.rm=T)-min(values(wtlg_ras), na.rm=T))
sote_ras<-subset(mod_pred, 'SOTE_indivSUM')
sote_ras<-(sote_ras-min(values(sote_ras), na.rm=T))/(max(values(sote_ras), na.rm=T)-min(values(sote_ras), na.rm=T))
nodd_ras<-subset(mod_pred, 'NODD_indivSUM')
nodd_ras<-(nodd_ras-min(values(nodd_ras), na.rm=T))/(max(values(nodd_ras), na.rm=T)-min(values(nodd_ras), na.rm=T))
tern_ras<-subset(mod_pred, 'TERN_indivSUM')
tern_ras<-(tern_ras-min(values(tern_ras), na.rm=T))/(max(values(tern_ras), na.rm=T)-min(values(tern_ras), na.rm=T))
 

```


```{r, echo=FALSE, warning=F, message=F}
pal <- colorBin(rev(c('#9e0142','#d53e4f','#f46d43','#fdae61','#fee08b','#e6f598','#abdda4','#66c2a5','#3288bd','#5e4fa2')), bins=10, c(NA, seq(0, 1, 0.1)), na.color = "transparent")

 m <- leaflet() %>%
  addTiles() %>% 
   
  addRasterImage(brbo_ras, colors = pal, opacity = 0.8, group='BRBO')%>%
   addRasterImage(mabo_ras, colors = pal, opacity = 0.8, group='MABO')%>%
   addRasterImage(rfbo_ras, colors = pal, opacity = 0.8, group='RFBO')%>%
   addRasterImage(frbd_ras, colors = pal, opacity = 0.8, group='FRBD')%>%
   addRasterImage(trbd_ras, colors = pal, opacity = 0.8, group='TRBD')%>%
   addRasterImage(wtst_ras, colors = pal, opacity = 0.8, group='WTST')%>%
   addRasterImage(wtlg_ras, colors = pal, opacity = 0.8, group='WTLG')%>%
   addRasterImage(sote_ras, colors = pal, opacity = 0.8, group='SOTE')%>%
   addRasterImage(nodd_ras, colors = pal, opacity = 0.8, group='NODD')%>%
   addRasterImage(tern_ras, colors = pal, opacity = 0.8, group='TERN')%>%
 
     addRasterImage(hotspots, colors = pal, opacity = 0.8, group='Hotspots') %>%
   addLegend(pal = pal, values = c(NA, seq(0, 1, 0.1)),
    title = "Likely foraging habitat") %>%
   
   addPolygons(data=filter(rad_diss, md_spgr=='BRBO'), fill=F, group='BRBO')%>%
   addPolygons(data=filter(rad_diss, md_spgr=='MABO'), fill=F, group='MABO')%>%
   addPolygons(data=filter(rad_diss, md_spgr=='RFBO'), fill=F, group='RFBO')%>%
   addPolygons(data=filter(rad_diss, md_spgr=='FRBD'), fill=F, group='FRBD')%>%
   addPolygons(data=filter(rad_diss, md_spgr=='TRBD'), fill=F, group='TRBD')%>%
   addPolygons(data=filter(rad_diss, md_spgr=='WTST'), fill=F, group='WTST')%>%
   addPolygons(data=filter(rad_diss, md_spgr=='WTLG'), fill=F, group='WTLG')%>%
   addPolygons(data=filter(rad_diss, md_spgr=='SOTE'), fill=F, group='SOTE')%>%
   addPolygons(data=filter(rad_diss, md_spgr=='NODD'), fill=F, group='NODD')%>%
   addPolygons(data=filter(rad_diss, md_spgr=='TERN'), fill=F, group='TERN')%>%
   
    addCircleMarkers(data=colz, popup= paste("Site:", colz$dsgntn_n , "<br>", 
                                             "Colony:", colz$site_nm,"<br>", "Species:", colz$species), stroke=F, radius=6, fillOpacity = 0.5)%>%
   
     addLayersControl(overlayGroups = c('BRBO', 'MABO', 'RFBO', 'FRBD', 'TRBD', 'WTST', 'WTLG',
                                        'SOTE', 'NODD', 'TERN', 'Hotspots'), options=layersControlOptions(collapsed=F))
   
m
```

